### PR TITLE
Fixes empty query parameters

### LINKED ISSUE #60: RequestBuilder should not add QueryParameters in the final URI if they are null or empty
Sourced from https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/564

When the query parameter is not set or empty, we should not add it to the Uri. 

Possilby we need a better check at https://github.com/microsoft/kiota-abstractions-dotnet/blob/89beebb57258163e44a962f8d4222488ef82febf/src/RequestInformation.cs#L53

### PR DESCRIPTION
**Pull request by andrueastman**
This PR closes #60

Changes include : - 

- Add checks to the  `AddQueryParameters` method to avoid adding empty collections and string to the `QueryParameters` when using request builders.

### CODE REVIEW

File: src/RequestInformation.cs [hunk 1]
```diff
@@ -105,8 +108,12 @@ public void AddQueryParameters(object source)
                                                 Value: x.GetValue(source)
                                             )
                                         )
-                                        .Where(x => x.Value != null && !QueryParameters.ContainsKey(x.Name)))
+                                        .Where(x =>  x.Value != null &&
+                                                    !QueryParameters.ContainsKey(x.Name) &&
+                                                    !string.IsNullOrEmpty(x.Value.ToString())))// no need to add an empty string value
             {
+                if(property.Value is ICollection collection && collection.Count == 0)
```
Comment (baywet) [inline src/RequestInformation.cs:115]: you can move that to the where filter

```CSharp
property.Value is not ICollection collection || collection.Count > 0
```

**Review by baywet — DISMISSED** [review]
Thanks for fixing this. Would you mind also checking Java/TS/Go please?

File: src/RequestInformation.cs (hunk 1 above)
Comment (andrueastman) [reply src/RequestInformation.cs]: Thanks for this.

**Review by baywet — APPROVED** [review]
